#! /bin/sh

picom &

flashfocus &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

pgrep -x sxhkd > /dev/null || sxhkd &

# feh --bg-fill /home/jimmy/Pictures/Wallpapers/scaledextend.png --bg-fill /home/jimmy/Pictures/Wallpapers/ricer.jpg &
feh --bg-fill /home/jimmy/Pictures/Wallpapers/nord5.jpg &

bash /home/jimmy/.config/polybar/launch.sh --grayblocks &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          40

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#81a1c1
bspc config active_border_color \#81a1c1
bspc config normal_border_color \#5E81AC

bspc rule -a zoom state=floating
bspc rule -a feh state=floating rectangle=1000x500+0+0 center=true
bspc rule -a chrome rectangle=1000x500+0+0 center=true
bspc rule -a thunar state=floating rectangle=1000x500+0+0 center=true
# bspc rule -a sxiv state=floating rectangle=367x367+1200+200
bspc rule -a kitty rectangle=1000x500+0+0 center=true
