#! /bin/sh

# -----[Autostart Applications]-----
pgrep -x sxhkd > /dev/null || sxhkd &
picom & # Compositor
flashfocus & # Shows active windows
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & # Manages GUI authenatication
bash ~/.config/polybar/launch.sh & # Status Bar

# -----[Xinput Configuration]-----
DEVICE_NAME="VEN_2C2F:00 2C2F:0025 Touchpad"
xinput --set-prop "$DEVICE_NAME" "libinput Accel Custom Motion Points" 0, 1, 3.5, 6.5, 10
xinput --set-prop "$DEVICE_NAME" "libinput Accel Custom Motion Step" 3
xinput --set-prop "$DEVICE_NAME" "libinput Scrolling Pixel Distance" 50

# -----[Wallpaper]-----
feh --bg-fill ~/Pictures/Wallpapers/"Nord-Mountains.png" &

# -----[BSPWM Configuration]-----
bspc monitor -d α β γ δ ε ζ η 
bspc config border_width         3
bspc config window_gap           20
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# -----[Border Colors]-----
# COLOR="#F7768E" # Tokyo Night
# COLOR="#A6ACCD" # Poimandres
# COLOR="#2E3440" # Invisible Nord Border
COLOR="#3B4252" # Lighter Nord Border
# COLOR="#5E81AC" # Bright Nord Border

bspc config focused_border_color "$COLOR"
bspc config active_border_color  "$COLOR"
bspc config normal_border_color  "$COLOR"

# -----[Window Rules]-----
bspc rule -a zoom state=floating
bspc rule -a feh state=floating rectangle=1000x500+0+0 center=true
bspc rule -a chrome rectangle=1000x500+0+0 center=true
bspc rule -a Thunar rectangle=1000x500+0+0 center=true
bspc rule -a kitty rectangle=500x370+0+0 center=true
