[packages]
pacman = [
  # Xorg
  "xorg-xinput",
  "xorg-xinit",
  "xorg-xrandr",

  # BSPWM (& SXHKD)
  "bspwm",
  "picom",
  "polkit-gnome",
  "fcitx5-im", "fcitx5-chinese-addons", "fcitx5-lua",
  "feh",

  # SXHKD (& BSPWM)
  "sxhkd",
  "dunst",
  "maim",
  "xclip",
  "brightnessctl",
  "pipewire-pulse",
  "rofi",

  # Thunar
  "thunar",
  "tumbler",
  "thunar-archive-plugin",
  "thunar-media-tags-plugin",
  "thunar-volman",
  "ntfs-3g",

  # Kitty
  "kitty",

  # Fonts
  "ttf-firacode-nerd",
  "ttf-jetbrains-mono-nerd",
  "noto-fonts-cjk",
  "noto-fonts-emoji",

  # GTK
  "lxappearance",
  "gtk-engine-murrine",

  # Neovim
  "neovim",
  "tree-sitter-cli",

  # Zathura
  "zathura",
  "zathura-pdf-mupdf",

  # Python/C++
  "pyenv",
  "python-termcolor",
  "clang",

  # LSPs
  "pyright",
  "marksman",
  "texlab",
  "lua-language-server",
  "ccls",

  # Formatters
  "stylua",
  "mdformat",
  
  # Misc. Utils
  "polybar",
  "networkmanager",
  "yazi",
  "plocate",

  # Texlive
  "texlive-basic",
  "texlive-bibtexextra",
  "texlive-binextra",
  "texlive-context",
  "texlive-fontsextra",
  "texlive-fontsrecommended",
  "texlive-fontutils",
  "texlive-formatsextra",
  "texlive-games",
  "texlive-humanities",
  "texlive-latex",
  "texlive-latexextra",
  "texlive-latexrecommended",
  "texlive-luatex",
  "texlive-mathscience",
  "texlive-metapost",
  "texlive-music",
  "texlive-pictures",
  "texlive-plaingeneric",
  "texlive-pstricks",
  "texlive-publishers",
  "texlive-xetex",

  # Developing this config
  "vhs"
]
