# A short tape (using charm_ "VHS") demo-ing the Chezmoi install process.
Output Venv-Selector-Demo.gif

Set FontSize 40
Set Width 2400
Set Height 1000
Set Padding 40
Set Theme "tokyonight"

# Setup Alias b/c ~/.bashrc isn't executed
Hide
Type "alias v='source ~/Documents/Environments/env_runner.sh'" 
Enter
Sleep 50ms
Type "clear"
Enter
Sleep 50ms
Show

# Initialize Chezmoi
Type "v"
Sleep 500ms
Enter
Sleep 3s

Type "1"
Sleep 500ms
Enter
Sleep 5s

